### ISSUE TITLE
Use rest parameters instead of `arguments`

### ISSUE THREAD

**Issue by mdibaiee** [lebab/lebab#16]

**Comment by benjamn** [comment]
This could be really awesome, especially if we also use `...spread` arguments instead of `.apply(obj, arguments)`, too.

**Comment by benjamn** [comment]
The trickiest part will be identifying and eliminating function calls that are meant to turn `arguments` into an array, like `Array.prototype.slice.call(arguments)` or `_.toArray(arguments)` (where `_` is bound to something like `require("underscore")`). Since those methods could do anything, it will never be totally safe to assume a certain behavior, but perhaps the user can provide input about what styles of array conversion are used in the codebase.

**Comment by nene** [comment]
The initial version of this transform has been implemented in Lebab 2.5.0.

Doesn't support detection of `Array.prototype.slice` and friends though. However the `.apply(this, arguments)` case is already covered by `arg-spread` transform.

**Comment by nene** [comment]
Closing this in favor of a follow-up issue: #191
