### ISSUE TITLE
Module.exports syntax for classes

### ISSUE THREAD

**Issue by watzon** [lebab/lebab#175]
Classes don't get generated if the javascript format is as follows

``` javascript
var ClassName = module.exports = function() {...}
```

This is basically the same as

``` javascript
export default class ClassName {}
```

**Comment by nene** [comment]
That's a tricky syntax to catch. Lebab implements two separate transforms which don't really know about each other:

- `class` transform will not recognize this as a class because of the module.exports in the middle of an assignment.
- `commonjs` transform will not recognize this as export because it only looks at assignments to module.exports at top-level.

I suppose one cold improve `commonjs` transform, so it would output the following:

```js
export default var ClassName = function() {...}
```

Then the `class` transform should recognize this function as a class.

Additional question is whether code like this is a widespread practice or something just you personally use. Some references to projects using this would be helpful.

**Comment by nene** [comment]
The solution proposed above isn't really good, as one would need to know that commonjs transform needs to be run before class transform. But given the state of support for the import/export syntax, it's likely that one wants to apply the commonjs transform as the very last.

This also looks like a very specific case. We could come back to this, when more requests for supporting such a pattern appear.

Closing for now.
