### ISSUE TITLE
Make possible to specify configuration file

### ISSUE THREAD

**Issue by evenfrost** [lebab/lebab#231]
It would be great if instead of providing explicit arguments every time we could specify a kind of `.lebabrc` file in directory where `lebab` is installed, in the form of:
```json
{
  "transforms": [
    "arrow",
    "for-of",
    "arg-spread",
    "obj-method",
    "obj-shorthand",
    "no-strict",
    "exponent",
    "multi-var",
    "let",
    "class",
    "template",
    "default-param"
  ]
}
```
And running `lebab` from this folder would respect this config.

**Comment by nene** [comment]
It's by design that lebab makes it inconvenient to run multiple transforms
in one go.

I'm not sure why would you add a config file for Lebab into your project. I
would assume one only uses Lebab once to convert his project to ES6, and
later it would be of little use.

20.04.2017 13:28 kirjutas kuupäeval "Aleksey Kislov" <
notifications@github.com>:
