### ISSUE TITLE
nested for statements are ignored when running for-each transform

### ISSUE THREAD

**Issue by capaj** [lebab/lebab#244]
see the screenshot:

![image](https://cloud.githubusercontent.com/assets/1305378/25942914/617f0efe-363e-11e7-9e67-ebc4f7f1c03a.png)

it would be nice if it was able to transform even nested loops.

**Comment by nene** [comment]
The problem is not about nested loops - Lebab can handle them just fine. If you were to remove the outer loop, you would see that Lebab would still not transform the inner one.

For the outer loop there's a variable declared for the current array element:

```js
const topicId = publishedTopicIds[i];
```

Lebab can safely convert that variable into `forEach()` parameter.

With the inner loop though, there is no such variable. Lebab would have to figure out a new variable name to introduce. If Lebab were meant to generate code just for the machine, some random name would work fine, but because the goal of Lebab is to produce code for human consumption, coming up with a suitable variable name is much trickier.

There's an issue for implementing this for `for-of` transform (which would apply for forEach transform as well): #169
