### ISSUE TITLE
Error "Only one instance of babel-polyfill is allowed" when using Lebab as library

### ISSUE THREAD

**Issue by jhonJerb** [lebab/lebab#249]
HI Guys,

While trying to use your tool in the browser with browserify I got sometimes errors:

**only one instance of babel-polyfill is allowed**

Any idea why? I just simply use the following code and sometimes it works and sometimes I got this error ...

var lebab = require('lebab');
const {code, warnings} = lebab.transform(es5Code);

Have you tried the latest version with browserify ? any hint how can I avoid this new instance creation ?

I saw that this error is coming from .../node_modules/babel-polyfill/lib/index.js
line10 .

Can I remove somehow the babel polyfill before Im calling your code since not sure from where it's coming...i'm not using babel...

Thanks

**Comment by nene** [comment]
Well, the reason seems obvious from the error message. Lebab uses `babel-polyfill` and likely your code also uses `babel-polyfill`.

It's a problem I've experienced in other projects using `babel-polyfill`. I guess the better way is to simply drop the use of it in Lebab and use `transform-runtime` Babel plugin instead - that's what the [babel-polyfill docs](https://babeljs.io/docs/usage/polyfill/) recommend for libraries.

**Comment by jhonJerb** [comment]
Thanks for quick response!
what do you mean by remove the babel-polyfill and use transfrom-runtime instead,
1. can you please explain how to do it?
2. does this change lebab functionality ?

**Comment by nene** [comment]
Well, if you want to do it by yourself, remove the use of `babel-polyfill` from Lebab code and replace it with `transform-runtime` plugin in `.babelrc`. Run all the tests: if they pass, great, if they fail, fix the errors. Then send in your pull request.

Good luck!

**Comment by jhonJerb** [comment]
Just to verify before I start doing that.... Im not using babel and in when I install lebab in the package json it uses    "babel-polyfill": "^6.9.1", you mean to change it to transform-runtime and run the test, am I right ?  (I didnt find any .babelrc file ...)

Thanks!

**Comment by nene** [comment]
Hmm... if you're not using babel by yourself, then this error isn't really caused by what I thought.

It might be that some other dependency within Lebab uses `babel-polyfill` which conflicts with the babel-polyfill used directly by Lebab itself. Could be caused by different `babel-polyfill` versions. I haven't updated the dependencies of Lebab for a while. Perhaps just upgrading these will solve the problem.

PS. `.babelrc` file sits right here: https://github.com/lebab/lebab/blob/master/.babelrc
Simply removing `babel-polyfill` from package.json won't work as Lebab code tries to import the library.

**Comment by jhonJerb** [comment]
exactly, Im not using babel...I use the latest version of lebab.

Few month ago we use lebab and we didnt got this errors .
when do you think we can try the new updated version ?

Thanks for your support!

**Comment by nene** [comment]
We'll see... perhaps I get to it today. But can't promise it.

Feel free to poke me when nothing happens in few days as I might have forgotten it.

**Comment by jhonJerb** [comment]
Sure thank you very much : )

**Comment by uniibu** [comment]
Since babel-polyfill occupies a global namespace `_babelPolyfill` and In case you don't want to add it via babelrc, you could also do a safe import by doing:
```js
if((typeof window !== 'undefined' && !window._babelPolyfill) || 
  (typeof global !== 'undefined' && !global._babelPolyfill)) {
  require('babel-polyfill')
}
```

**Comment by nene** [comment]
@jhonJerb I've upgraded all Lebab dependencies and done a release of Lebab 2.4.7.

You can give a try if this helps anything.

**Comment by uniibu** [comment]
I've encountered the same thing a few days back, and it was not mostly lebab's fault but was also from another module that i used on the same project. If you only use lebab and browserify it, it shouldn't give any errors. So i suggest check your project's dependencies and see if any of them uses babel-polyfill. You could also (on ubuntu) do `grep -R babel-polyfill ./node_modules` which would search your modules folder recursively for any instance of babel-polyfill.

**Comment by JenneyJ** [comment]
@nene , Thanks I've tried with the latest version and it seems that the issue it still occur  :( .

I think that I found from where the issue is coming

We are using ES-LINT and it seems that when you are doing browserify it use babel-polyfill

Therefore I've two questions

If I comment the error from Lebab 
..../WebstormProjects/transpiler/node_modules/babel-polyfill/lib/index.js

// if (global._babelPolyfill) {
//   throw new Error("only one instance of babel-polyfill is allowed");
// }

This can do some problem with Lebab ? since I suppose that this is part of some devDep 

When I try it Lebab code is working but not sure which problem I can get in the future ...

Thanks!!!

**Comment by nene** [comment]
If you comment this out, then babel-polyfill will get loaded multiple times. I gouess babel-polyfill authors chose to disallow this, because [core-js](https://github.com/zloirock/core-js) (which is also imported by this file) similarly disallows this practice in its docs:

> Warning: if you use core-js with the extension of native objects, require all needed core-js modules at the beginning of entry point of your application, otherwise, conflicts may occur.

I don't know what the implications might be.

Anyway... now that I'm sure that the problem really comes from multiple imports of babel-polyfill, my plan is to explore getting rid of it in Lebab.

BTW, if you don't mind asking, what are you using Lebab for? It's pretty rare to see it used as a library.

**Comment by JenneyJ** [comment]
Thanks it will be great if you can remove it...
We are working on some POC (and after testing maybe use it in production if it's stable...)  to add it to some enterprise IDE (like in VS code addon for lebab) and we want to enable it for JS developers to switch es5 -> es6 code or to get some idea how the code should look like.  Lebab doing some great job of doing so and we want to use it.

Does it make sense?  :-) 

Thanks!

**Comment by nene** [comment]
Great to hear that it's helping you :)

2017-07-31 14:16 GMT+03:00 JenneyJ <notifications@github.com>:

**Comment by nene** [comment]
@jhonJerb @JenneyJ I've dropped the `babel-polyfill` dependency and released Lebab 2.7.5. Check out if it solves your issue.

**Comment by JenneyJ** [comment]
Thanks I'm doing some pre-testing and it's works great. since this error doesn't occur always I need to test it more ... but until now it's working great! Thank you very much!!!

**Comment by codejamninja** [comment]
Idempotent Babel Polyfill can be imported multiple times

```sh
npm install --save idempotent-babel-polyfill
```

```js
import 'idempotent-babel-polyfill';
```
