### ISSUE TITLE
Lodash cherry-picking

### ISSUE THREAD

**Issue by uniibu** [lebab/lebab#255]
It would be nice if you could atleast cherry pick lodash functions that you specifically use. It would make install faster and build smaller.  

Example `import forEach from 'lodash/forEach'`

**Comment by nene** [comment]
I wonder how much difference that would make.

It wouldn't help much if some dependency of Lebab also depended on Lodash. I checked though and luckily none of them do.

Lebab does use a fair chunk of these Lodash utilities:

- assign (can be replaced with Object.assign())
- values
- min
- includes
- find
- isEqual
- isArray
- isString
- isObjectLike
- matches
- isMatchWith
- isEqualWith
- flatten
- compact
- tail
- sortBy
- capitalize
- omit
- mapValues
- uniq

Still... that's several times less than in the full Lodash library.

Luckily the chaining is used fairly little, so that code could be rewritten pretty easily.

**Comment by uniibu** [comment]
Here is a sample gist i made for some lodash functions
https://gist.github.com/uniibu/49cfd3f8b27464792b1b88f444c0b0c1

**Comment by nene** [comment]
Thanks, this certainly looks way smaller than the full Lodash.

**Comment by nene** [comment]
Finally implemented this by importing individual functions from `lodash/fp`, like:

    import {flow, compact, map} from 'lodash/fp';

I'm not 100% sure if Webpack and/or browserify will be able to take advantage from it and tree-shake the unnecessary parts out of the build.

**Comment by uniibu** [comment]
Good job on implementing `lodash/fp` . It should also be noted for other devs that by using `lodash/fp`, the order of the arguments changed, in particular the data argument has been moved to the last position.

**Comment by nene** [comment]
Shouldn't be a problem, as there aren't really much contributors to Lebab :)

I guess you're the only active one besides me.
