### ISSUE TITLE
`arrow-return` breaks on functions with a single empty return statement

### ISSUE THREAD

**Issue by atjn** [lebab/lebab#343]
Hello and thank you for making this very cool tool :)

Running the `arrow-return`  transform on the following code:
```
() => {
	return;
}
```

Produces this code:
```
() => 
```

That is a syntax error, and it will often crash `lebab` internally because the next transform is unable to read the code. It should have produced the following:
```
() => {}
```

**Comment by rbatllet** [comment]
I guess this project decided to take a long vacation in Bali with no internet connection. Bon voyage!

**Comment by nene** [comment]
Well, thanks for the support @rbatllet. In fact I was on a vacation, cycling my way across France, and while doing so I didn't really care about what's happening in the internet.

**Comment by rbatllet** [comment]
Everyone wants to be famous these days, even Github projects. I suppose you have retired to pursue your career as a rock star as well.

**Comment by nene** [comment]
@atjn Thanks for the bug report and pull requests.

I fixed the bug for now so that this case is simply not transformed. As the goal of this transform is to convert the cases where the shorthand notation for returning value from array function can be used, it doesn't seem right for this transform to simply eliminate the return and leave an empty `{}` block.

At least that'll take care of the crashing. I'm not sure how frequently such empty return code comes up in the wild. Perhaps it should be transformed, but for now I'll lean on the side of not to, as such empty function with an empty return inside it was completely unnecessary even in the ES5 world, so it doesn't really fit into the domain of modernizing the code, but rather it's in the realm of generally eliminating unnecessary code, which is somewhat out of scope for this tool. A tool like ESLint can be used to eliminate these empty returns.

**Comment by atjn** [comment]
Thank you for fixing this @nene and doing it so quickly!

IMO this can still fall inside `lebab`'s scope.
The codebase I am transforming contains a lot of noops like these, which I think are hard to read and understand in a big file with a lot of code:

```js
function () {
 return;
}
```
Since `lebab`'s main goal essentially is to make the code more streamlined and easier to read, I think this transition is the most optimal:
```js
() => {}
```
Keeping the `return` statement actually makes the function less readable for me, as I don't have the `function` keyword to make it clear that the `return` is wrapped in a small function.
If you want to keep it in line with always returning a value, you could also do:
```js
() => undefined;
```
But this is not a big issue for me and I also understand your arguments against it. As long as the transform produces code without syntax errors, I am happy :)
